# Site settings
title: Eternity Engineering
email: andrew@xyncro.com
description: "Blog"
baseurl: ""
url: "https://eternity.engineering"

# Build settings

encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: pretty
